# note: The lists ids/frames/sizes and tag_ids/tag_names/tag_frames must match.

"/fixed_camera/apriltag":
  ros__parameters:
    image_transport: raw
    family: 36h11
    size: 0.060
    max_hamming: 0
    pose_estimation_method: pnp
    profile: false

    detector:
      threads: 4
      decimate: 1.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    tag:
      ids:
        [
          0, 1, 2, 3, 4,
          5, 6, 7, 8, 9,
          10, 11, 12, 13, 14,
          15, 16, 17, 18, 19
        ]

      frames:
        [
          tag_0, tag_1, tag_2, tag_3, tag_4,
          tag_5, tag_6, tag_7, tag_8, tag_9,
          tag_10, tag_11, tag_12, tag_13, tag_14,
          tag_15, tag_16, tag_17, tag_18, tag_19
        ]

      sizes:
        [
          0.060, 0.060, 0.060, 0.060, 0.060,
          0.060, 0.060, 0.060, 0.060, 0.060,
          0.060, 0.060, 0.060, 0.060, 0.060,
          0.060, 0.060, 0.060, 0.060, 0.060
        ]

"/fixed_camera/tag_tracker":
  ros__parameters:
    detections_topic: /fixed_camera/detections
    output_namespace: /brewbot/perception/fixed_camera

    # Empty initially: poses are published in the Azure Kinect image frame.
    # Later set this to kitchen_world after camera-to-world calibration.
    target_frame: ""

    tag_ids: [
          0, 1, 2, 3, 4,
          5, 6, 7, 8, 9,
          10, 11, 12, 13, 14,
          15, 16, 17, 18, 19
        ]
    tag_names: [Ntag_0, Ntag_1, Ntag_2, Ntag_3, Ntag_4,
          Ntag_5, Ntag_6, Ntag_7, Ntag_8, Ntag_9,
          Ntag_10, Ntag_11, Ntag_12, Ntag_13, Ntag_14,
          Ntag_15, Ntag_16, Ntag_17, Ntag_18, Ntag_19]
    tag_frames:
      [
        tag_0, tag_1, tag_2, tag_3, tag_4,
          tag_5, tag_6, tag_7, tag_8, tag_9,
          tag_10, tag_11, tag_12, tag_13, tag_14,
          tag_15, tag_16, tag_17, tag_18, tag_19
      ]

    minimum_decision_margin: 15.0
    minimum_consecutive_detections: 1
    maximum_detection_gap_sec: 2.0
    lost_timeout_sec: 1.5
    publish_rate_hz: 10.0
